# Generated by Django 4.1.1 on 2022-10-10 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_rename_fan_nomi_bloktestlar_fio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloktestlar',
            name='week_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
