# Generated by Django 4.1.1 on 2022-10-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_bloktestlar_week_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloktestlar',
            name='week_date',
            field=models.DateField(),
        ),
    ]
