# Generated by Django 4.1.1 on 2022-10-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_bloktestlar_week_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantest',
            name='teacher',
            field=models.CharField(default="G'ulomov Azizbek", max_length=100),
        ),
    ]
