# Generated by Django 4.1.1 on 2022-10-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0002_botusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusers',
            name='telegram',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
