# Generated by Django 4.1.1 on 2022-10-12 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentstudent_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstudent',
            name='sum',
            field=models.CharField(default=django.utils.timezone.now, max_length=600),
            preserve_default=False,
        ),
    ]
