# Generated by Django 4.1.1 on 2022-10-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_options_alter_student_table'),
        ('payment', '0003_paymentstudent_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentstudent', to='students.student'),
        ),
    ]
