# Generated by Django 4.1.1 on 2022-10-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_one_id'),
        ('class', '0004_alter_classroom_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', to_field='one_id')),
            ],
        ),
    ]
