# Generated by Django 4.1.1 on 2022-10-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0007_alter_davomat_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='davomat',
            name='bool',
            field=models.BooleanField(default=False),
        ),
    ]
