# Generated by Django 4.1.1 on 2022-10-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(max_length=500, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
